#!/usr/bin/env php
<?php
/*
Created, designed, and implemented by Michael Latman 
© Copyright 2012 Dugley Labs. This product was made under contract of Kraft estates and should not be distributed to 3rd parties without the prior consent of the creator.
*/

//SELECT * FROM `visitors` WHERE NOW() > DATE_ADD(`last_seen`, INTERVAL 36 MINUTE) LIMIT 0, 30


function Dlog($message) {
	$myFile = "/home/dotcloud/current/cronlog.txt";
	$fh = fopen($myFile, 'a+') or die("can't open file");
	fwrite($fh, date('l\, F jS\, Y ').': '.$message."\n");
	fclose($fh);
}

Dlog("Cron ran ---- ");

$env = json_decode(file_get_contents("/home/dotcloud/environment.json"), true);
//echo $env['DOTCLOUD_DATA_MONGODB_URL'];
$conn = new Mongo($env['DOTCLOUD_DATA_MONGODB_URL']);

$db = $conn->SimCRM;



$collection = $db->visitors;
$collection->remove(array('name' => null));

$tenMinutesAgo = new DateTime();
$tenMinutesAgo->modify('-15 minutes');
//echo($tenMinutesAgo);
	$search = array('updated' => array('$lte' => $tenMinutesAgo));
$cursor = $collection->remove($search);


$collection = $db->estates;
$collection->remove(array('estate' => null));

$collection = $db->users;
$vcollection = $db->visitors;

$longTime = new DateTime();
$longTime->modify('-15 days');
//echo($tenMinutesAgo);
	$search = array('last_seen' => array('$lte' => $longTime));
$cursor = $collection->remove($search);


$oneMinutesAgo = new DateTime();
$oneMinutesAgo->modify('-2 minutes');
	$search = array('updated' => array('$ne' => null, '$lte' => $oneMinutesAgo));
$cursor = $collection->find($search);

foreach ($cursor as $doc) { 
	Dlog($doc['name'].' appears to be offline.. Last seen '.$doc['updated']);
	$search = array('locked_by' => $doc['key']);
	$find = $vcollection->find($search);
	foreach ($find as $doc2) {
		$doc2['locked_by'] = null;
		$vcollection->save($doc2);
	}
	$doc['last_seen'] = $doc['updated'];
	$doc['updated'] = null;
	$collection->save($doc);
}

exit(0);

?>